server:
  port: 8099
spring:
  application:
    name: consents
  data:
    mongodb:
      uri: mongodb://consent:consent@localhost:27017/consentdb?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

external:
  github:
    api:
      url: https://api.github.com

