server:
  port: 8099
spring:
  application:
    name: consents
  data:
    mongodb:
      uri: mongodb://consent:consent@localhost:27017/consentdb?authSource=admin



external:
  github:
    api:
      url: https://api.github.com

