version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_consent
    environment:
      MONGO_INITDB_ROOT_USERNAME: consent
      MONGO_INITDB_ROOT_PASSWORD: consent
      MONGO_INITDB_DATABASE: consentdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
